### ISSUE TITLE
Default columns added to table even when they are already listed as delegators

### ISSUE THREAD

**Issue by pkokorev** [bfg-s/admin#1]
**Code:**

![image](https://github.com/bfg-s/admin/assets/5184701/8610f6e6-15d4-4425-8505-01c2c5589821)

**Result:**

![image](https://github.com/bfg-s/admin/assets/5184701/409c8cb2-f12b-4dac-89e2-dca49bee771b)

**Expected result:**

Framework checks for duplicates before applying `colDefault`.

![image](https://github.com/bfg-s/admin/assets/5184701/f5a8f5ca-b15b-4a6f-a314-c2b739dd4aae)

**Comment by Xsaven** [comment]
`colDefault` - adds 3 columns by default`id`, `created_at` and `updated_at`
![image](https://github.com/bfg-s/admin/assets/1726771/109051dd-2b98-4aa1-892d-36dcce41e737)

**Comment by Xsaven** [comment]
what version of the panel?

**Comment by Xsaven** [comment]
Update to version 6.2.3. Befor sortedModelTable you can send you delegate `->withModelTableClass($modelTable)->sortedModelTable(...)` for default columns. And for the standard fields id, created_at and updated_at, I added an existence check
