### ISSUE TITLE
Dropdown input: Allow sorting entities by fields located in relations

### ISSUE THREAD

**Issue by pkokorev** [bfg-s/admin#2]
Same as label composition in the `load` method, I would be nice to have the possibility to sort the dropdown entries by a field located in the entity's relation.

Example:
![image](https://github.com/bfg-s/admin/assets/5184701/629b8121-bfe5-4edf-ab02-636985a89a87)

**Comment by Xsaven** [comment]
Added this feature in version 6.4.0 https://bfg-s.github.io/admin-documentation/change-logs.html#6-4-0-2024-07-02

**Comment by Xsaven** [comment]
https://bfg-s.github.io/admin-documentation/change-logs.html#6-4-0-2024-07-02
